services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: course_recommendation
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'